# In-Memory Database (No installation required)
spring.datasource.url=jdbc:h2:mem:morphlogdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console to see your data in the browser (at localhost:8080/h2-console)
spring.h2.console.enabled=true

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=morphlog-backend
server.port=8080
